#!/bin/bash

APPLY_INDEX[kubectlk]=apply-kubectlk
apply-kubectlk(){

  kubectl apply -k $1

}

APPLY_INDEX[kubectlf]=apply-kubectlf
apply-kubectlf(){

  kubectl apply -f $1

}

APPLY_INDEX[kbuild]=apply-kbuild
apply-kbuild(){

  kustomize build $1 | kubectl apply -f -

}

APPLY_INDEX[bash]=execute-bash
execute-bash(){

  bash $1

}

APPLY_INDEX[terraform]=apply-terraform
apply-terraform(){

  terraform init $1
  terraform apply -auto-approve $1

}

APPLY_INDEX[playbook]=apply-playbook
apply-playbook(){

  ansible-playbook $1 --extra-vars "operation=apply"

}

APPLY_INDEX[chart]=apply-chart
apply-chart(){

  INSTALL_NAME=$(sed s/\://g <<< $name)
  if helm list -q | grep ${INSTALL_NAME}
  then
    helm upgrade ${INSTALL_NAME} $1
  else
    helm install ${INSTALL_NAME} $1
  fi

}