#!/bin/bash

APPLY_INDEX[kubectlk]=apply-kubectlk
apply-kubectlk(){

  kubectl apply -k $1

}

APPLY_INDEX[kubectlf]=apply-kubectlf
apply-kubectlf(){

  kubectl apply -f $1

}

APPLY_INDEX[kbuild]=apply-kbuild
apply-kbuild(){

  kustomize build $1 | kubectl apply -f -

}

APPLY_INDEX[bash]=execute-bash
execute-bash(){

  bash $1

}