#!/bin/bash
 

DELETE_INDEX[kubectlk]=delete-kubectlk
delete-kubectlk(){

  kubectl delete -k $1

}

DELETE_INDEX[kubectlf]=delete-kubectlf
delete-kubectlf(){

  kubectl delete -f $1

}

DELETE_INDEX[kbuild]=delete-kbuild
delete-kbuild(){

  kustomize build $1 | kubectl delete -f -

}

DELETE_INDEX[terraform]=delete-terraform
delete-terraform(){

  cd $1
  terraform init -input=false
  terraform destroy -auto-approve
  cd -

}

DELETE_INDEX[playbook]=delete-playbook
delete-playbook(){

  ansible-playbook $1 --extra-vars "operation=delete"

}

DELETE_INDEX[chart]=delete-chart
delete-chart(){

  helm uninstall $(sed s/\://g <<< $name)

}